name: Build Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Install Maui Workload
        run: dotnet workload install maui-android
        
      - name: Build
        working-directory: ./src
        run: dotnet build -c Release -f net6.0-android

      - name: Test
        working-directory: ./src
        run: dotnet test -c Release -f net6.0-android

