name: Build Avalonia Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  POWERSHELL_TELEMETRY_OPTOUT: true

jobs:
  maui-windows:
    runs-on: windows-2022    
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "APP_VERSION=$ver" >> $env:GITHUB_OUTPUT
        
      - name: Build
        working-directory: .\src
        shell: pwsh
        run: |
          dotnet publish Jellyfin.Avalonia -c Release -r win-x64 --output artifacts

     
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: windows-avalonia-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: ${{ github.workspace}}\src\artifacts            
            
