name: Build MacCatalyst

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  maui-maccatalyst:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=${{ env.GITHUB_RUN_NUMBER }}
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION=$ver" >> $GITHUB_ENV

      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Build
        working-directory: ./src
        run: dotnet build -c Release -f net6.0-maccatalyst

      - name: Test
        working-directory: ./src
        run: dotnet test -c Release -f net6.0-maccatalyst

      #- name: Upload MacCatalyst build artifacts
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: maccatalyst-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
      #    path: '*maccatalyst/**/*.app/**'