name: Build Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  POWERSHELL_TELEMETRY_OPTOUT: true

jobs:
  maui-windows:
    runs-on: windows-2022    
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Setup .NET
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3
        with:
          dotnet-version: 7.0.x

      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "APP_VERSION=$ver" >> $env:GITHUB_OUTPUT

      - name: Install Maui Workload
        run: dotnet workload install maui-windows
        
      - name: Build
        working-directory: .\src
        shell: pwsh
        run: |
          dotnet publish Jellyfin.Maui -c Release -f net7.0-windows10.0.19041.0 /p:RuntimeIdentifierOverride=win10-x64
          New-Item -Path . -Name "artifacts" -ItemType Directory
          Get-ChildItem -Path Jellyfin.Maui*.msix -Recurse -File | Copy-Item -Destination .\artifacts\

      - name: Sign installer
        uses: GabrielAcostaEngler/signtool-code-sign@65c104a80f652b927e6237dc6c5b12a1b0cd18b0 # v1
        with:
          certificate: ${{ secrets.WIN_SIGN_CERT }}
          cert-password: ${{ secrets.WIN_CERT_PASSWORD }}
          cert-sha1: ${{ secrets.WIN_CERT_SHA1 }}
          folder: '.\src\artifacts'

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: windows-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: |             
            .\src\artifacts\Jellyfin.Maui*.msix
