name: Build Avalonia macOS

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  POWERSHELL_TELEMETRY_OPTOUT: true

jobs:
  avalonia-macos:
    runs-on: macos-14   
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
        with:
          dotnet-version: |
            8.0.x

      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=$GITHUB_RUN_NUMBER
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT
        
      - name: Build
        working-directory: ./src
        shell: pwsh
        run: |
          dotnet publish Jellyfin.Avalonia -r osx-x64 --output artifacts/Jellyfin.Avalonia

     
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: macos-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: ${{ github.workspace}}/src/artifacts            
            
