name: Build Avalonia Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  POWERSHELL_TELEMETRY_OPTOUT: true

jobs:
  avalonia-linux:
    runs-on: ubuntu-22.04   
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=$GITHUB_RUN_NUMBER
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT
        
      - name: Build
        working-directory: ./src
        shell: pwsh
        run: |
          dotnet publish Jellyfin.Avalonia -c Release -r linux-x64 --self-contained --output artifacts/Jellyfin.Avalonia

     
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: linux-avalonia-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: ${{ github.workspace}}/src/artifacts            
            
