name: Build MacCatalyst

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Build
        working-directory: ./src
        run: dotnet build -c Release -f net6.0-maccatalyst

      - name: Test
        working-directory: ./src
        run: dotnet test -c Release -f net6.0-maccatalyst
