name: Build MacCatalyst

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  maui-maccatalyst:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3

      - name: Setup .NET
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3
        with:
          dotnet-version: 7.0.x

      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=$GITHUB_RUN_NUMBER
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION::$ver >> $GITHUB_OUTPUT"

      - name: Install Maui Workload
        run: dotnet workload install maui-maccatalyst
        
      - name: Build
        working-directory: ./src
        run: |
          dotnet build -f net7.0-maccatalyst -c Release -o ./artifacts
          dotnet publish -f net7.0-maccatalyst -c Release -p:BuildIpa=True -o ./artifacts

      - name: Upload MacCatalyst build artifacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: maccatalyst-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: ./src/artifacts/**/*.pkg
