name: Build Apple

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        framework: [ net6.0-ios, net6.0-maccatalyst ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Build
        working-directory: ./src
        run: dotnet build -c Release -f ${{ matrix.framework }}

      - name: Test
        working-directory: ./src
        run: dotnet test -c Release -f ${{ matrix.framework }}
