name: Build Android

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "::set-output name=APP_VERSION::$ver"

      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Build
        working-directory: ./src
        run: dotnet build -c Release -f net6.0-android

      - name: Test
        working-directory: ./src
        run: dotnet test -c Release -f net6.0-android

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: '*Android\**\*-Signed.apk'

