name: Lint XAML

on:
  push:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3

      - name: Setup .NET
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # tag=v3
        with:
          dotnet-version: 7.0.x

      - name: Lint XAML
        working-directory: ./src
        run: |
          dotnet tool restore
          dotnet xstyler --recursive --directory . --passive
